### PR TITLE
format import

### PR DESCRIPTION
**Pull request by chemidy**
gofmt on import

### CODE REVIEW

**Comment by hiranya911** [comment]
@chemidy just a ping on the question abov. Do we need to do something extra to get CI to catch this sort of issues>

**Comment by chemidy** [comment]
You do not have to change anything.

I'm using vscode and by default the formatTool is not gofmt but goreturns : 

```
  // Pick 'gofmt', 'goimports', 'goreturns' or 'goformat' to run on format.
  "go.formatTool": "goreturns",
```

Check this [link]( http://goinbigdata.com/goimports-vs-gofmt/) for more informations

[goreturns is based on goimports](https://github.com/sqs/goreturns)

**Comment by Tkbagz** [comment]
What do you mean

**Comment by hiranya911** [comment]
@chemidy it sounds like we should change our CI script (`.travis.gofmt.sh`) to use `goimports` instead of `gofmt`. But we can do that in a separate PR.

**Pull request merged**
