### PR TITLE
Fixing package path

### PR DESCRIPTION
**Pull request by mblasi**
Hey there! So you want to contribute to a Firebase SDK? 
Before you file this pull request, please read these guidelines:

### Discussion

  * Read the contribution guidelines (CONTRIBUTING.md).
  * If this has been discussed in an issue, make sure to link to the issue here. 
    If not, go file an issue about this **before creating a pull request** to discuss.

### Testing

  * Make sure all existing tests in the repository pass after your change.
  * If you fixed a bug or added a feature, add a new test to cover your code.

### API Changes

  * At this time we cannot accept changes that affect the public API.  If you'd like to help 
    us make Firebase APIs better, please propose your change in an issue so that we 
    can discuss it together.

Hi guys!

Not sure why, but it is like the context package path is wrong... either I'm loosing something or it cant work as is.

Please, let me know if the fix looks good for you, It fixes my app in my environment.

Regards,
Matías.

### CODE REVIEW

**Comment by mblasi** [comment]
I signed it!

**Comment by hiranya911** [comment]
`golang.org/x/net/context` and `context` refer to the same thing. The latter was introduced in golang 1.7 (see the [godocs](https://godoc.org/golang.org/x/net/context)). 

In order to support older go distributions, we use the former everywhere in our code. This is probably not necessary though, since most users are on golang 1.7 and above. But that should be done everywhere in the SDK, not just the storage package.

**Comment by mblasi** [comment]
I understand, but I'm using golang 1.9.1... should it work too?

**Comment by hiranya911** [comment]
It should. Our CI environment compiles and tests the SDK on go1.9 it seems: https://travis-ci.org/firebase/firebase-admin-go/builds/296402828

**Pull request closed without merging**
