### PR TITLE
chore: Merging v4 branch into dev

### PR DESCRIPTION
**Pull request by hiranya911**
Contains modules support and other breaking API changes.

API CHANGE: Admin SDK has opted into Go modules. The package name now has the major version appended to it. Developers should use the new package name `firebase.google.com/go/v4` when installing and importing the SDK.
RELEASE NOTE: change(fcm): The `messaging.WebpushFcmOptions` type has been renamed to `messaging.WebpushFCMOptions`.
RELEASE NOTE: feat(fcm): Added new service-level error checking functions `IsThirdPartyAuthError()`, `IsQuotaExceeded()`, `IsSenderIDMismatch()`, `IsUnregistered()` and `IsUnavailable()`.
RELEASE NOTE: feat: Added a new `errorutils` package that provides functions for checking for platform-level error codes.
RELEASE NOTE: feat(auth): Added new service-level error checking functions `IsIDTokenInvalid()`, `IsIDTokenExpired()`, `IsSessionCookieInvalid()`, `IsSessionCookieExpired()` and `IsCertificateFetchFailed()`. These functions can be used in conjunction with the existing JWT verification APIs provided by the SDK.

### CODE REVIEW

**Comment by cee-dub** [comment]
These important release notes didn’t make it into your published changes for the release. Could you fix that by hand, maybe?

**Comment by hiranya911** [comment]
@cee-dub those comments were certainly included in the published released notes: https://firebase.google.com/support/release-notes/admin/go#version_400_-_16_june_2020

**Comment by cee-dub** [comment]
@hiranya911 ah, thank you. I was looking here https://github.com/firebase/firebase-admin-go/releases/tag/v4.0.0

**Comment by hiranya911** [comment]
@cee-dub Ah, I see what you mean. That section is a simple changelog generated off of git commit messages, and therefore PR descriptions usually get ignored. However, since this release contains some important changes, it might be useful to have that information on that page as well. I'll look into it.

**Pull request merged**
