### PR TITLE
feat(rtdb): Support RTDB Emulator via FIREBASE_DATABASE_EMULATOR_HOST

### PR DESCRIPTION
**Pull request by kenshin54**
### Discussion

This PR added the support of RTDB Emulator, discussion is here #298 

### Testing

I have manually ran the unit tests and integration tests and verified that they pass. Now we can also test them against the emulator by the environment variable `FIREBASE_DATABASE_EMULATOR_HOST`.

For example:
```bash
FIREBASE_DATABASE_EMULATOR_HOST=http://localhost:9000/?ns=foo-default-rtdb go test ./db
FIREBASE_DATABASE_EMULATOR_HOST=http://localhost:9000/?ns=foo-default-rtdb go test ./integration/db
```

### API Changes

No public API changes

### CODE REVIEW

**Comment by wesselvanderlinden** [comment]
:+1:

**Review by yuchenshi — CHANGES_REQUESTED** [review]
The environment variable format is not a full URL but only the host and port, such as `localhost:9000`, `[::1]:8080` or `my-rtdb.local`. Query params through that env var aren't supported in other SDKs either. Otherwise LGTM.

**Comment by wesselvanderlinden** [comment]
Can this be looked at? We really need this to be merged :)

**Comment by r-LaForge** [comment]
Hey @kenshin54,
I would have really liked to have used this.
Is there a reason this was closed beyond inactivity?

**Pull request closed without merging**
