### PR TITLE
Bug fix #489

### LINKED ISSUE #489: StandardScrypt has incorrect key for MemoryCost when creating http request
### Describe your environment

  * Operating System version: macOS Monterey V12.3
  * Firebase SDK version: 4
  * Library version: 4.7.1
  * Firebase Product: auth

### Describe the problem

ImportUsers request failed with INVALID_HASH_PARAMETERS. After digging through the code and comparing with the Node SDK I noticed that the key for `hash.StandardScrypt.MemoryCost` was different between the two. When marshaling the hash config into an http request, the correct key for that field is `"cpuMemCost"`, as opposed to `"memoryCost"`, which is the current value.

#### Steps to reproduce:

Make an ImportUsers request with `hash.StandardScrypt` hash config as an option.

#### Relevant Code:

```
var client *auth.Client
// Initialize client

config := hash.StandardScrypt{
	MemoryCost:       1024,
	Parallelization:  16,
	BlockSize:        8,
	DerivedKeyLength: 64,
}

_, err := client.ImportUsers(ctx, users, auth.WithHash(config))
```

#### Firebase response:
```
{
  "error": {
    "code": 400,
    "message": "INVALID_HASH_PARAMETER",
    "errors": [
      {
        "message": "INVALID_HASH_PARAMETER",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
```

### Fix:
Just change the key value returned from `hash.StandardScrypt.Config()` to `"cpuMemCost"`. Should I just do this with a PR? Your guidelines said to post an issue first. Thanks!

### PR DESCRIPTION
**Pull request by pragatimodi**
Changing the key value "MemoryCost" returned from hash.StandardScrypt.Config() to "cpuMemCost"

RELEASE NOTE: Fixed an incorrect key used to set `MemoryCost` config in `hash.StandardScrypt.Config()` API

### CODE REVIEW

**Comment by prameshj** [comment]
cc @lahirumaramba

**Review by prameshj — APPROVED** [review]

**Comment by lahirumaramba** [comment]
Hi @pragatimodi Thank you for the PR! Would you be able to change the base to `dev`, please?

**Review by lahirumaramba — APPROVED** [review]
Thanks! LGTM!

**Pull request merged**
