### PR TITLE
Update comment align with code

### PR DESCRIPTION
**Pull request by castor-rtzr**
Update comment align with #453

### CODE REVIEW

**Comment by hiranya911** [comment]
@castor-rtzr thanks for the PR. Please sign the CLA before we can accept it.

**Comment by castor-rtzr** [comment]
@googlebot I signed it!

**Review by hiranya911 — CHANGES_REQUESTED** [review]
Thanks for the PR @castor-rtzr. I think there's a trailing space in one of the lines which is causing an error. Can you fix that or just run gofmt on the file to reformat it?

**Comment by castor-rtzr** [comment]
> Thanks for the PR @castor-rtzr. I think there's a trailing space in one of the lines which is causing an error. Can you fix that or just run gofmt on the file to reformat it?

Fixed it! :-)

**Review by hiranya911 — APPROVED** [review]
Thanks. LGTM 👍

**Pull request merged**
