### PR TITLE
Moving the snippets to the main repo.

### PR DESCRIPTION
**Pull request by avishalom**

### CODE REVIEW

**Comment by samtstern** [comment]
@avishalom well that was fast!  Before I start reading the code, is this just a straight copy-and-paste from snippets-go?

**Comment by avishalom** [comment]
Yes, it is actually a very slow copy and paste :-)

**Comment by samtstern** [comment]
@avishalom I think we're missing something in the `.travis.yml` that makes sure these compile?

**Comment by avishalom** [comment]
go test -v -test.short ./...
builds everything, (i tried inserting errors. but couldn't get them to pass...)

**Pull request closed without merging**
