### PR TITLE
Reading FCM error code from details section

### PR DESCRIPTION
**Pull request by hiranya911**
Porting the error handling improvement over from https://github.com/firebase/firebase-admin-node/pull/246

### CODE REVIEW

**Comment by nordicdyno** [comment]
Any plans to expose Error.Details to client code?  I badly need it.

**Comment by hiranya911** [comment]
No plans to expose `Error.Details`. Can you explain your use case a bit more in detail? Error handling in the Go SDK is about to undergo some changes, and we can consider new requirements when we get to that.

**Comment by nordicdyno** [comment]
I want have ability to know which kind of error is happened and process it accordingly. Simple example:  group errors by type in monitoring counters.

Also it 's good Go practice to use typed errors not just simple error strings (that's ok for simple programs, but not for public APIs).

* https://blog.golang.org/error-handling-and-go

**Comment by hiranya911** [comment]
That's the direction we are heading. But I can't comment on the timeline yet.

**Comment by nordicdyno** [comment]
Nice! I'm glad to hear that. Right now I can patch library code by myself, but it would be much better to avoid it when API improved.

**Pull request merged**
