### PR TITLE
feat(fcm): Set FCMOptions for MulticastMessage

### PR DESCRIPTION
**Pull request by FZambia**
Hello!

Currently it's impossible to set `FCMOptions` for `MulticastMessage`. While for example in Python admin SDK [this is possible](https://github.com/firebase/firebase-admin-python/blob/5c21b81e35443f749a5df16e7e02dd817dca8c1c/firebase_admin/_messaging_encoder.py#L86). And [in Java admin SDK](https://github.com/firebase/firebase-admin-java/blob/e8ec68c97929972acdbe05b79b5ea18f077a08a2/src/main/java/com/google/firebase/messaging/MulticastMessage.java#L68). This pull request fixes this.

### CODE REVIEW

**Comment by FZambia** [comment]
CLA signed

**Comment by FZambia** [comment]
Hello team, could you please tell when this will be released?

**Comment by FZambia** [comment]
@lahirumaramba - any updates?

**Comment by FZambia** [comment]
Guys, at least explain what prevents you from merging this?

**Comment by chong-shao** [comment]
LGTM But I'd like to ask for waiting until @lahirumaramba 's review

**Review by chong-shao — APPROVED** [review]

**Comment by sebastianbuechler** [comment]
This would be nice to finally have in the package. @lahirumaramba can you please have a look at this minor change as it's only two lines of code and almost a year open?

**Comment by FZambia** [comment]
@lahirumaramba kindly reminding 🙏

**Review by lahirumaramba — APPROVED** [review]
LGTM!

**Comment by lahirumaramba** [comment]
Thanks folks! This change will be included in the next release

**Comment by FZambia** [comment]
Nice, many thanks!

**Pull request merged**
